import Employees from "./Employees/Employees";

const EmployeesContainer = () => {
  const employees = [
    {
      id: "1",
      name: "Ken",
      last_name: "Bauer",
      email: "ken@ibm.mx",
      role: "Manager",
    },
    {
      id: "2",
      name: "Carla",
      last_name: "Jimenez",
      email: "carla@ibm.mx",
      role: "Front-End Developer",
    },
    {
      id: "3",
      name: "Sara",
      last_name: "Garcia",
      email: "sara@ibm.mx",
      role: "Back-End Developer",
    },
    {
      id: "4",
      name: "John",
      last_name: "Doe",
      email: "johndoe@ibm.mx",
      role: "QA Engineer",
    },
    {
      id: "5",
      name: "Jane",
      last_name: "Smith",
      email: "janesmith@ibm.mx",
      role: "UX Designer",
    },
    {
      id: "6",
      name: "Peter",
      last_name: "Anderson",
      email: "peteranderson@ibm.mx",
      role: "Systems Administrator",
    },
    {
      id: "7",
      name: "Mary",
      last_name: "Jones",
      email: "maryjones@ibm.mx",
      role: "Marketing Manager",
    },
    {
      id: "8",
      name: "David",
      last_name: "Brown",
      email: "davidbrown@ibm.mx",
      role: "Sales Representative",
    },
    {
      id: "9",
      name: "Susan",
      last_name: "Green",
      email: "susangreen@ibm.mx",
      role: "Customer Service Representative",
    },
    {
      id: "10",
      name: "Alex",
      last_name: "Smith",
      email: "alexsmith@ibm.mx",
      role: "Data Scientist",
    },
    {
      id: "11",
      name: "Emily",
      last_name: "Jones",
      email: "emilyjones@ibm.mx",
      role: "Software Engineer",
    },
    {
      id: "12",
      name: "Michael",
      last_name: "Brown",
      email: "michaelbrown@ibm.mx",
      role: "Product Manager",
    },
    {
      id: "13",
      name: "Juan",
      last_name: "Rodriguez",
      email: "juanrodriguez@ibm.mx",
      role: "Software Engineer",
      nationality: "Mexican",
    },
    {
      id: "14",
      name: "Maria",
      last_name: "Gonzalez",
      email: "mariagonzalez@ibm.mx",
      role: "UX Designer",
      nationality: "Puerto Rican",
    },
    {
      id: "15",
      name: "Pedro",
      last_name: "Sanchez",
      email: "pedrosanches@ibm.mx",
      role: "Systems Administrator",
      nationality: "Cuban",
    },
    {
      id: "16",
      name: "Wang",
      last_name: "Li",
      email: "wangli@ibm.mx",
      role: "Software Engineer",
      nationality: "Chinese",
    },
    {
      id: "17",
      name: "Zhang",
      last_name: "Su",
      email: "zhangsu@ibm.mx",
      role: "UX Designer",
      nationality: "Chinese",
    },
    {
      id: "18",
      name: "Chen",
      last_name: "Wu",
      email: "chenwu@ibm.mx",
      role: "Systems Administrator",
      nationality: "Chinese",
    },
    {
      id: "19",
      name: "Fang",
      last_name: "Zhao",
      email: "fangzhao@ibm.mx",
      role: "Marketing Manager",
      nationality: "Chinese",
    },
    {
      id: "20",
      name: "Sun",
      last_name: "Qian",
      email: "sunqian@ibm.mx",
      role: "Sales Representative",
      nationality: "Chinese",
    },
    {
      id: "21",
      name: "Li",
      last_name: "Yang",
      email: "liyang@ibm.mx",
      role: "Customer Service Representative",
      nationality: "Chinese",
    },
    {
      id: "22",
      name: "Liu",
      last_name: "Zhang",
      email: "liuzhang@ibm.mx",
      role: "Data Scientist",
      nationality: "Chinese",
    },
    {
      id: "23",
      name: "Wu",
      last_name: "Chen",
      email: "wuchen@ibm.mx",
      role: "Software Engineer",
      nationality: "Chinese",
    },
    {
      id: "24",
      name: "Guan",
      last_name: "Wang",
      email: "guanwang@ibm.mx",
      role: "Product Manager",
      nationality: "Chinese",
    },
  ];

  return <Employees employees={employees} />;
};

export default EmployeesContainer;
